blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/organicmaps/organicmaps/discussions
    about: Discuss the usage of Oma, ask questions, or talk about ideas that aren't yet actionable.
  - name: Translations
    url: https://github.com/organicmaps/organicmaps/blob/master/docs/TRANSLATIONS.md
    about: Translate Oma into your language
  - name: News
    url: https://organicmaps.app/news/
    about: Check the latest project news
